### ISSUE TITLE
System.PlatformNotSupportedException in .Net Standard 2.0

### ISSUE THREAD

**Issue by andeq** [mparlak/Flee#87]
We are currently developing a UWP App which should use Flee for Expression Evaluation.  Unfortunately in the Release Build we get a System.PlatformNotSupportedException. 

> System.PlatformNotSupportedException: 'Dynamic code generation is not supported on this platform.'

`   at System.Reflection.Emit.DynamicMethod..ctor(String name, Type returnType, Type[] parameterTypes) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Reflection\Emit\ReflectionEmitThrower.cs:line 11
   at Flee.InternalTypes.Expression`1.CreateDynamicMethod()
   at Flee.InternalTypes.Expression`1.Compile(String expression, ExpressionOptions options)
   at Flee.InternalTypes.Expression`1..ctor(String expression, ExpressionContext context, Boolean isGeneric)`

Flee 1.2.2 ist referenced in a .Net Standard 2.0 Project. Flee should support .Net Standard 2.0, but Apparently DynamicMethod isn`t supported in .Net Standard 2.0: [DynamicMethod Class](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.dynamicmethod?view=net-5.0&viewFallbackFrom=netstandard-2.0)

How can this be possible? How can we user Flee with .Net Standard 2.0 and UWP?

**Comment by jl0pd** [comment]
Library need to use multi-targeting and add `net461`, `netcoreapp2.0`, `uap10.0` or maybe others to list of targets. [Docs](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting#multi-targeting)

**Comment by hunkydoryrepair** [comment]
> Library need to use multi-targeting and add `net461`, `netcoreapp2.0`, `uap10.0` or maybe others to list of targets. [Docs](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting#multi-targeting)

How would this resolve the issue of UWP not supporting dynamic code generation? Cannot use Reflection.Emit, which is pretty much all Flee does. It generates dynamic code.
